export const USER_SLP_ADDRESS_UPDATED = 'profile/user/USER_SLP_ADDRESS_UPDATED';
export const USER_TOTAL_POINTS_UPDATED = 'profile/user/USER_TOTAL_POINTS_UPDATED';
export const USER_LAST_ZERO_POINTS_DATE_UPDATED = 'profile/user/USER_LAST_ZERO_POINTS_DATE_UPDATED';
export const WITHDRAW = 'profile/user/USER_LAST_ZERO_POINTS_DATE_UPDATED';
export const ADD_FREE_POINTS = 'profile/user/ADD_FREE_POINTS';
export const MAKE_ANSWER = 'profile/user/MAKE_ANSWER';
export const UPDATE_FREE_POINTS_AVAILABLE = 'profile/user/UPDATE_FREE_POINTS_AVAILABLE';
export const UPDATE_WITHDRAWS_AVAILABLE = 'profile/user/UPDATE_WITHDRAWS_AVAILABLE';

